[package]
name = "fdr-show-indexer-server"
version = "0.1.0"
authors = ["Tommy Volk <tvolk131@gmail.com>"]
edition = "2018"

[dependencies]
chrono       = "0.4.19"
futures-lite = "1.11.3"
hyper        = { version = "0.14.7", features = ["full"] }
reqwest      = { version = "0.11.3", default-features = false, features = ["json", "rustls-tls"] }
serde        = { version = "1.0.126", features = ["derive"] }
serde_json   = "1.0.64"
tokio        = { version = "1.6.0", features = ["rt-multi-thread", "macros"] }
url          = "2.2.2"