[package]
name = "fdr-show-indexer-server"
version = "0.1.0"
authors = ["Tommy Volk <tvolk131@gmail.com>"]
edition = "2018"

[dependencies]
chrono        = "0.4.19"
reqwest       = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls"] }
rocket        = "0.4.10"
serde         = { version = "1.0.126", features = ["derive"] }
serde_json    = "1.0.64"
sonic-channel = { version = "0.4.0", features = ["search", "ingest"] }
tokio         = { version = "1.8.1", features = ["rt-multi-thread", "macros"] }
url           = "2.2.2"