[package]
name = "fdr-show-indexer-server"
version = "0.1.0"
authors = ["Tommy Volk <tvolk131@gmail.com>"]
edition = "2018"

[dependencies]
bson         = "1.2.2"
futures-lite = "1.11.3"
hyper        = { version = "0.14.7", features = ["full"] }
mongodb      = { version = "1.2.1", default-features = false, features = ["async-std-runtime"] } # TODO - Remove default-features and features, which will revert from async-std runtime to tokio. We need this right now because the current version of this dependency (at least at time of writing) is running on tokio 0.2.
serde_json   = "1.0.64"
tokio        = { version = "1.6.0", features = ["rt-multi-thread", "macros"] }
url          = "2.2.2"