[package]
name = "fdr-show-indexer-server"
version = "0.1.0"
authors = ["Tommy Volk <tvolk131@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.5.0", features = ["rt-multi-thread", "macros"] }
hyper = { version = "0.14.7", features = ["full"] }