[package]
name = "fdr-show-indexer-server"
version = "0.1.0"
authors = ["Tommy Volk <tvolk131@gmail.com>"]
edition = "2018"

[dependencies]
chrono          = "0.4.19"
futures         = "0.3.16"
meilisearch-sdk = "0.9.0"
reqwest         = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls"] }
rocket          = "0.4.10"
serde           = { version = "1.0.127", features = ["derive"] }
serde_json      = "1.0.66"
sonic-channel   = { version = "0.4.1", features = ["search", "ingest"] }
tokio           = { version = "1.9.0", features = ["rt-multi-thread", "macros"] }
url             = "2.2.2"